### ISSUE TITLE
onDismiss optional closure for Sheets & FullScreenCovers

### ISSUE THREAD

**Issue by JamesSedlacek** [JamesSedlacek/Presenting#5]
This would add the ability to write an onDismiss completion handler closure for sheets and fullScreenCovers.

https://developer.apple.com/documentation/swiftui/view/sheet(ispresented:ondismiss:content:)

The sheet view modifier has an optional onDismiss closure that we want the ability to use.

Usage Example:

```swift
presenter.presentSheet(.settings, onDismiss: {
    print("Sheet dismissed!")
})

presenter.presentSheet(.settings) {
    print("Sheet dismissed!")
}

presenter.presentFullScreenCover(.settings, onDismiss: {
    print("FullScreenCover dismissed!")
})

presenter.presentFullScreenCover(.settings) {
    print("FullScreenCover dismissed!")
}
```

**Comment by JorgeAGomez** [comment]
https://developer.apple.com/documentation/swiftui/view/sheet(item:ondismiss:content:)
